### ISSUE TITLE
[Question] : Lorentzian Classification and history

### ISSUE THREAD

**Issue by wtc0der** [techfreaque/octobot-lorentzian-classification#4]
Hi.
I think this Machine Learning strategy can't realy work with Kukoin Exchange. 
Indeed, Kukoin limit the history download for 200 candles.
I believe Machine Learning need more candles for work correctly, isn't it ?
I don't know if Octobot keeps candle history?
Anyway, this project is a great initiative, congratulations :-)

**Comment by techfreaque** [comment]
Thank you :)

You could run it with 200 candles but it wont perform well.
I just checked the kucoin api, so it would support it, but it needs to be fixed in ccxt/octobot.
If you want, I would also offer paid work, this should take 250$ - 500$, we can make a fixed price once I took a look at the issue.

**Comment by wtc0der** [comment]
No thanks, Your offer seem to be fair but I don't want to pay for that, I hope you understand :-)
I think I'll try to connect Octobot on Tiingo API witch I adrealy have an account for another bot
